name: Test-Workflow

on:
  pull_request:
    branches: [ "master" ]

jobs:
  fetch:
    runs-on: self-hosted
    steps:
    - name: Setup environment
      run: |
        rm -f ci-env
        echo "SSH_PRV_KEY='/home/pi/.ssh/id_ed25519'" >> ci-env
        echo "SSH_PUB_KEY='/home/pi/.ssh/id_ed25519.pub'" >> ci-env
        echo "REPO_NAME=$(echo ${{ github.repository }})" >> ci-env
        echo "DOCKER_IMAGE_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> ci-env
        echo "DOCKER_NAME"="docker-runner" >> ci-env
        echo "ARTIFACTS"=$(basename ${{ github.repository }}'-artifacts') >> ci-env
        echo "WINDOW_NAME"="MidiPlayer" >> ci-env
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          echo "BRANCH_NAME=$(echo ${{ github.head_ref }})" >> ci-env
        else
          echo "BRANCH_NAME=$(echo ${{ github.ref }})" >> ci-env
        fi
        echo "BIN"="MidiPlayer" >> ci-env

    - name: Remove existing docker and artifacts
      run: |
        . ./ci-env
        # Force stop and remove existing docker
        docker stop $DOCKER_NAME > /dev/null || true
        docker rm $DOCKER_NAME > /dev/null || true
        rm -rf $ARTIFACTS/builds

    - name: Docker build
      run: |
        . ./ci-env
        cd /home/pi/DockerTest && \
        docker build -t $DOCKER_IMAGE_NAME \
        --secret id=ssh_prv_key,src=$SSH_PRV_KEY \
        --secret id=ssh_pub_key,src=$SSH_PUB_KEY \
        --build-arg repo_name=$REPO_NAME \
        --build-arg branch_name=$BRANCH_NAME \
        --build-arg DATE=$(date +%s) .

  build:
    runs-on: self-hosted
    needs:
      - fetch
    steps:
    - name: Start docker
      run: |
        . ./ci-env
        cat ./ci-env >> $GITHUB_ENV # Usefull for deploy builds step
        docker run -d --name $DOCKER_NAME $DOCKER_IMAGE_NAME

    - name: "Compile project ${{ github.repository }} for aarch64 Linux"
      run: |
        . ./ci-env
        docker exec docker-runner cmake -S . -B build_aarch64_linux -DCMAKE_TOOLCHAIN_FILE=./cmake/aarch64_Linux_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
        docker exec docker-runner make -C build_aarch64_linux -j $(nproc)
        mkdir -p $ARTIFACTS/builds/build_aarch64_linux && docker cp "$DOCKER_NAME:$REPO_NAME/build_aarch64_linux" $ARTIFACTS/builds/build_aarch64_linux
        find $ARTIFACTS/builds/build_aarch64_linux/build_aarch64_linux -mindepth 1 \
          ! -path "$ARTIFACTS/builds/build_aarch64_linux/build_aarch64_linux/${BIN}" \
          ! -path "$ARTIFACTS/builds/build_aarch64_linux/build_aarch64_linux/resources" \
          ! -path "$ARTIFACTS/builds/build_aarch64_linux/build_aarch64_linux/resources/*" \
          -exec rm -rf {} +

    - name: "Compile project ${{ github.repository }} for x86_64 Linux"
      run: |
        . ./ci-env
        docker exec docker-runner sh -c 'echo "deb [arch=amd64] http://deb.debian.org/debian buster main" >> /etc/apt/sources.list'
        docker exec docker-runner sh -c 'echo "deb [arch=amd64] http://deb.debian.org/debian-security buster/updates main" >> /etc/apt/sources.list'
        docker exec docker-runner sh -c 'echo "deb [arch=amd64] http://deb.debian.org/debian buster-updates main" >> /etc/apt/sources.list'
        docker exec docker-runner apt-get update
        docker exec docker-runner dpkg --add-architecture amd64
        docker exec docker-runner apt-get install libglu1-mesa-dev:amd64 libasound2-dev:amd64 -y
        docker exec docker-runner cmake -S . -B build_x86_64_linux -DCMAKE_TOOLCHAIN_FILE=./cmake/x86_64_Linux_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
        docker exec docker-runner make -C build_x86_64_linux -j $(nproc)
        mkdir -p $ARTIFACTS/builds/build_x86_64_linux && docker cp "$DOCKER_NAME:$REPO_NAME/build_x86_64_linux" $ARTIFACTS/builds/build_x86_64_linux
        find $ARTIFACTS/builds/build_x86_64_linux/build_x86_64_linux -mindepth 1 \
          ! -path "$ARTIFACTS/builds/build_x86_64_linux/build_x86_64_linux/${BIN}" \
          ! -path "$ARTIFACTS/builds/build_x86_64_linux/build_x86_64_linux/resources" \
          ! -path "$ARTIFACTS/builds/build_x86_64_linux/build_x86_64_linux/resources/*" \
          -exec rm -rf {} +

    - name: "Compile project ${{ github.repository }} for x86_64 Windows"
      run: |
        . ./ci-env
        docker exec docker-runner cmake -S . -B build_x86_64_windows -DCMAKE_TOOLCHAIN_FILE=./cmake/x86_64_Windows_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
        docker exec docker-runner make -C build_x86_64_windows -j $(nproc)
        mkdir -p $ARTIFACTS/builds/build_x86_64_windows && docker cp "$DOCKER_NAME:$REPO_NAME/build_x86_64_windows" $ARTIFACTS/builds/build_x86_64_windows
        find $ARTIFACTS/builds/build_x86_64_windows/build_x86_64_windows -mindepth 1 \
          ! -path "$ARTIFACTS/builds/build_x86_64_windows/build_x86_64_windows/${BIN}.exe" \
          ! -path "$ARTIFACTS/builds/build_x86_64_windows/build_x86_64_windows/resources" \
          ! -path "$ARTIFACTS/builds/build_x86_64_windows/build_x86_64_windows/resources/*" \
          -exec rm -rf {} +

    - name: "Deploy aarch64 Linux build"
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build_aarch64_linux
        path: |
          ${{ env.ARTIFACTS }}/builds/build_aarch64_linux

    - name: "Deploy x86_64 Linux build"
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build_x86_64_linux
        path: |
          ${{ env.ARTIFACTS }}/builds/build_x86_64_linux

    - name: "Deploy x86_64 Windows build"
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build_x86_64_windows
        path: |
          ${{ env.ARTIFACTS }}/builds/build_x86_64_windows

    - name: "Docker clean up"
      if: always()
      run: |
        . ./ci-env
        # Force stop and remove existing docker
        docker stop $DOCKER_NAME > /dev/null || true
        docker rm $DOCKER_NAME > /dev/null || true
        rm -rf builds

  test:
    runs-on: self-hosted
    needs:
      - build
    steps:
    - name: Start docker
      run: |
        . ./ci-env
        cat ./ci-env >> $GITHUB_ENV # Usefull for deploy builds step
        docker run -d --device /dev/snd:/dev/snd --group-add audio --name $DOCKER_NAME $DOCKER_IMAGE_NAME
    - name: Remove previous artifacts
      run: |
        . ./ci-env
        rm -rf build_aarch64_linux
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: build_aarch64_linux
        path: ./
    - name: Copy build to docker
      run: |
        . ./ci-env
        docker exec docker-runner sh -c "rm -rf *"
        docker cp ./build_aarch64_linux docker-runner:/$REPO_NAME
        docker exec docker-runner chown -R 0:0 ./build_aarch64_linux
        docker exec docker-runner chmod +x ./build_aarch64_linux/$BIN
    - name: Setup audio and video server
      run: |
        docker exec docker-runner sh -c "Xorg :0 -config /etc/X11/xorg.conf &"
        docker exec docker-runner sh -c "pulseaudio&"
    - name: Run the app for 10 seconds
      run: |
        . ./ci-env
        docker exec -d docker-runner sh -c "DISPLAY=:0 ./build_aarch64_linux/$BIN"
        sleep 10
        docker exec docker-runner sh -c "DISPLAY=:0 xdotool search --name $WINDOW_NAME windowclose"
    - name: "Docker clean up"
      if: always()
      run: |
        . ./ci-env
        # Force stop and remove existing docker
        docker stop $DOCKER_NAME > /dev/null || true
        docker rm $DOCKER_NAME > /dev/null || true
        rm -rf builds
